{{- range .Values.istio -}}
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: {{.name}}-destination-rule
  namespace: {{.namespace}}
spec:
  host: {{.serviceName}}
  trafficPolicy:
    tls:
      mode: {{.tlsMode}}
---
{{- end -}} 