version: "2"
services:

  # Jaeger
  jaeger-all-in-one:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger-gin-go
    restart: always
    ports:
      - "16696:16686"
      - "14268"
      - "14250"

  # Collector
  otel-collector:
    image: ${OTELCOL_IMG}
    container_name: otel-gin-go
    restart: always
    command:
      [
        "--config=/etc/otel-collector-config.yaml",
        "${OTELCOL_ARGS}"
      ]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "1888:1888" # pprof extension
      - "8888:8888" # Prometheus metrics exposed by the collector
      - "8889:8889" # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "4327:4317" # OTLP gRPC receiver
      - "55679:55679" # zpages extension
    depends_on:
      - jaeger-all-in-one

  prometheus:
    container_name: prometheus-gin-go
    image: prom/prometheus:latest
    restart: always
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  #  album-store:
  #    build:
  #      dockerfile: Dockerfile
  #      context: .
  #    restart: always
  #    environment:
  #      - -otel-location=localhost:4327
  #      - -namespace=no-namespace
  #      - -instance-name=album-store-1
  #    ports:
  #      - "9080:9080"
  #    depends_on:
  #      - otel-collector

