apiVersion: k3d.io/v1alpha4
kind: Simple
servers: 1 # same as `--servers 1`
agents: 2 # same as `--agents 2`
ports:
  - port: 8070:80 # same as `--port '8070:80@loadbalancer'` # http default
    nodeFilters:
      - loadbalancer
registries: # define how registries should be created or used
  create: # creates a default registry to be used with the cluster; same as `--registry-create registry.local`
    name: registry.local
    host: "0.0.0.0"
    hostPort: "54094"
    volumes:
      - /tmp/registry:/var/lib/registry # persist registry data locally
options:
  k3s:
    extraArgs:
      - arg: --disable=traefik
        nodeFilters:
          - server:*
