apiVersion: skaffold/v2beta22
kind: Config
metadata:
   name: ingress-nginx
profiles:
   - name: k3d
     activation:
       - kubeContext: k3d-k3s-default
     deploy:
       helm:
         releases:
           - name: ingress-nginx
             remoteChart: ingress-nginx
             repo: https://kubernetes.github.io/ingress-nginx
             namespace: kube-system
             createNamespace: true
             valuesFiles: ["./install/values/local/nginx-ingress.values.yaml"]
---
apiVersion: skaffold/v2beta22
kind: Config
metadata:
   name: prometheus
profiles:
   - name: k3d
     activation:
       - kubeContext: k3d-k3s-default
     deploy:
       helm:
         releases:
           - name: prometheus
             remoteChart: prometheus
             repo: https://prometheus-community.github.io/helm-charts
             namespace: monitoring
             createNamespace: true
             valuesFiles: ["./install/values/local/prometheus.values.yaml"]
---
apiVersion: skaffold/v2beta22
kind: Config
metadata:
  name: grafana
profiles:
  - name: k3d
    activation:
      - kubeContext: k3d-k3s-default
    deploy:
      helm:
        releases:
          - name: grafana
            remoteChart: grafana
            repo: https://grafana.github.io/helm-charts
            namespace: monitoring
            createNamespace: true
            valuesFiles: ["./install/values/local/grafana.values.yaml"]
---
apiVersion: skaffold/v2beta22
kind: Config
metadata:
  name: jaeger
profiles:
  - name: k3d
    activation:
      - kubeContext: k3d-k3s-default
    deploy:
      helm:
        releases:
          - name: jaeger-all-in-one
            remoteChart: jaeger-all-in-one
            repo: https://raw.githubusercontent.com/hansehe/jaeger-all-in-one/master/helm/charts
            namespace: observability
            createNamespace: true
            valuesFiles: ["./install/values/local/jaeger-all-in-one.values.yaml"]
            wait: true # needed when otel-collector sends data to jaeger but not currently.
---
apiVersion: skaffold/v2beta22
kind: Config
metadata:
  name: opentelemetry-collector-k3d
profiles:
  - name: k3d
    activation:
      - kubeContext: k3d-k3s-default
    deploy:
      helm:
        releases:
          - name: opentelemetry-collector
            remoteChart: opentelemetry-collector
            repo: https://open-telemetry.github.io/opentelemetry-helm-charts
            namespace: observability
            createNamespace: true
            valuesFiles: ["./install/values/local/opentelemetry-collector.values.yaml"]
---
apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: dashboard
profiles:
  - name: k3d
    activation:
      - kubeContext: k3d-k3s-default
    deploy:
      helm:
        releases:
          - name: kubernetes-dashboard
            remoteChart: kubernetes-dashboard
            repo: https://kubernetes.github.io/dashboard/
            namespace: kubernetes-dashboard
            createNamespace: true
            valuesFiles: ["./install/values/local/dashboard.values.yaml"]
---
apiVersion: skaffold/v2beta22
kind: Config
metadata:
  name: album-store
profiles:
  - name: k3d
    activation:
      - kubeContext: k3d-k3s-default
    deploy:
      helm:
        releases:
          - name: album-store
            chartPath: ./helm/album-store
            namespace: album-store
            createNamespace: true
            valuesFiles: ["./install/values/local/album-store.values.yaml"]
---
apiVersion: skaffold/v2beta22
kind: Config
metadata:
  name: proxy-service
profiles:
  - name: k3d
    activation:
      - kubeContext: k3d-k3s-default
    deploy:
      helm:
        releases:
          - name: proxy-service
            chartPath: ./helm/proxy-service
            namespace: proxy-service
            createNamespace: true
            valuesFiles: ["./install/values/local/proxy-service.values.yaml"]