---
apiVersion: skaffold/v4beta2
kind: Config
metadata:
  name: album-store
profiles:
  - name: k3d
    activation:
      - kubeContext: k3d-k3s-default
    deploy:
      helm:
        releases:
          - name: album-store
            chartPath: ./install/helm/album-store
            namespace: album-store
            createNamespace: true
            valuesFiles: ["./install/values/local/album-store.values.yaml"]
---
apiVersion: skaffold/v4beta2
kind: Config
metadata:
  name: proxy-service
profiles:
  - name: k3d
    activation:
      - kubeContext: k3d-k3s-default
    deploy:
      helm:
        releases:
          - name: proxy-service
            chartPath: ./install/helm/proxy-service
            namespace: proxy-service
            createNamespace: true
            valuesFiles: ["./install/values/local/proxy-service.values.yaml"]