apiVersion: skaffold/v4beta2
kind: Config
metadata:
  name: dashboard
profiles:
  - name: k3d
    activation:
      - kubeContext: k3d-k3s-default
    deploy:
      helm:
        releases:
          - name: kubernetes-dashboard
            remoteChart: kubernetes-dashboard
            repo: https://kubernetes.github.io/dashboard/
            namespace: kubernetes-dashboard
            createNamespace: true
            valuesFiles: ["./install/values/local/dashboard.values.yaml"]
---
apiVersion: skaffold/v4beta2
kind: Config
metadata:
  name: istio
profiles:
  - name: k3d
    activation:
      - kubeContext: k3d-k3s-default
    deploy:
      helm:
        releases:
          - name: istio-base
            remoteChart: base
            repo: https://istio-release.storage.googleapis.com/charts
            namespace: istio-system
            createNamespace: true
            valuesFiles: ["./install/values/local/istio-base.values.yaml"]
          - name: istiod
            remoteChart: istiod
            repo: https://istio-release.storage.googleapis.com/charts
            namespace: istio-system
            createNamespace: true
            valuesFiles: ["./install/values/local/istio-istiod.values.yaml"]
          - name: istio-ingressgateway
            remoteChart: gateway
            repo: https://istio-release.storage.googleapis.com/charts
            namespace: istio-system
            createNamespace: true
            valuesFiles: ["./install/values/local/istio-gateway.values.yaml"]
          - name: kiali
            remoteChart: kiali-server
            repo: https://kiali.org/helm-charts
            namespace: istio-system
            createNamespace: true
            valuesFiles: ["./install/values/local/kiali-server.values.yaml"]
---
apiVersion: skaffold/v4beta2
kind: Config
metadata:
  name: istio-ingresses
profiles:
  - name: k3d
    activation:
      - kubeContext: k3d-k3s-default
    deploy:
      helm:
        releases:
          - name: istio-ingress-charts
            chartPath: ./install/helm/istio-ingress-charts # comment out repoChart and repo to use local version
            #  remoteChart: istio-ingress-charts
            #  repo: https://mcarr-and.github.io/go-gin-otelcollector/install/helm/charts
            namespace: default
            valuesFiles: ["./install/values/local/istio-ingress.values.yaml"]
