version: "3.9"
x-default-logging:
  &logging
  driver: "json-file"
  options:
    max-size: "5m"
    max-file: "2"

services:
  # Jaeger Tracing
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    restart: always
    ports:
      - "16696:16686"
      - "16686" # internal prometheus port
      - "14268" # jaeger.thrift
      - "14250" # model.proto
      - "4317" # otel grpc
      - "4318" # otel http
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    logging: *logging
  # Open Telemetry Collector 
  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: otel-collector
    restart: always
    command:
      [ "--config=/etc/otel-collector-config.yaml",
        "--config=/etc/otelcol-config-extras.yml"
      ]
    volumes:
      - ./config/otel-collector-config.yaml:/etc/otel-collector-config.yaml
      - ./config/otelcollector/otel-collector-config-extras.yaml:/etc/otelcol-config-extras.yml
    ports:
      - "1888" # pprof extension
      - "8888" # Prometheus metrics exposed by the collector
      - "8889" # Prometheus exporter metrics
      - "9464" # Prometheus exporter
      - "13133" # health_check extension
      - "4327:4317" # OTLP gRPC receiver
      - "4317" # internal OTLP gRPC receiver
      - "4318" # OTLP http receiver
      - "55679:55679" # zpages extension
    depends_on:
      - jaeger
    logging: *logging
  # Prometheus Metrics Collection
  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    restart: always
    volumes:
      - ./config/prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    logging: *logging
  # Grafana Metrics Dashboard
  grafana:
    image: grafana/grafana:9.1.0
    container_name: grafana
    volumes:
      - ./config/grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./config/grafana/provisioning/:/etc/grafana/provisioning/
    ports:
      - "3000:3000"
    logging: *logging
