{{- if .Values.istio.enabled }}
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ include "album-store.fullname" . }}-gateway
  namespace: {{.Release.Namespace}}
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: {{.Values.istio.gatewayPort}}
        name: {{lower .Values.istio.protocol}}-{{ include "album-store.fullname" . }}
        protocol: {{.Values.istio.protocol}}
      hosts:
        - "{{.Values.istio.host}}"
{{- end }}