{{- if .Values.istio.enabled }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "album-store.fullname" . }}-virtual-service
  namespace: {{.Release.Namespace}}
spec:
  hosts:
    - "{{.Values.istio.host}}"
  gateways:
    - {{ include "album-store.fullname" . }}-gateway
  http:
    - route:
        - destination:
            host: album-store
            port:
              number: {{.Values.istio.portNumber}}
{{- end }}