apiVersion: v1
kind: Service
metadata:
  namespace: "album-store"
  name: "album-store"
  annotations:
    prometheus.io/probe: "true"
    prometheus.io/probe-path: /status
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "9080"
  labels:
    app.kubernetes.io/instance: "album-store"
    app.kubernetes.io/name: "album-store"
    app.kubernetes.io/version: "0.1.0"
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - protocol: TCP
      name: http
      port: 9080
      targetPort: 9080
  selector:
    app.kubernetes.io/instance: "album-store"
    app.kubernetes.io/name: "album-store"
    app.kubernetes.io/version: "0.1.0"
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    test:
      "album-store"
    app.kubernetes.io/component: "album-store"
    app.kubernetes.io/instance: "album-store"
    app.kubernetes.io/name: "album-store"
    app.kubernetes.io/version: "0.1.0"
  name: "album-store"
  namespace: "album-store"
spec:
  containers:
    - name: "album-store"
      image: registry.local:54094/album-store:0.2.2 # use the cluster internal name to reference registry
      imagePullPolicy: Always
      env:
        - name: INSTANCE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: OTEL_LOCATION
          value: "opentelemetry-collector.observability.svc.cluster.local:4317"
        - name: GRPC_GO_LOG_VERBOSITY_LEVEL
          value: "99"
        - name: GRPC_GO_LOG_SEVERITY_LEVEL
          value: "info"
      ports:
        - name: http
          containerPort: 9080
          protocol: TCP
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"
      livenessProbe:
        httpGet:
          path: /status
          port: http
        initialDelaySeconds: 1
        periodSeconds: 5
  dnsPolicy: ClusterFirst # must be `ClusterFirst` to allow nginx to route to it via the ingress
  restartPolicy: Always
  terminationGracePeriodSeconds: 30
---
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: album-store-gateway
  namespace: album-store
spec:
  selector:
    istio: ingressgateway # use istio default controller
    namespace: istio-system
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "album-store.local"
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: album-store
  namespace: album-store
spec:
  parentRefs:
    - name: album-store-gateway
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /albums
        - path:
            type: Exact
            value: /status
        - path:
            type: Exact
            value: /metrics
        - path:
            type: PathPrefix
            value: /v3/api-docs/
      backendRefs:
        - name: album-store
          port: 9080
